### ISSUE TITLE
Meta: Allow validation without showing error messages

### ISSUE THREAD

**Issue by jzaefferer** [jquery-validation/jquery-validation#1349]
This is a very common issue that comes in many forms.

I'm going to close related issues as duplicates of this one.

**Comment by yanickrochon** [comment]
Wow! This issue is quite long standing!

I just came across this, while performing `form.valid()` and saw that it returned `true`, even though some required fields were blank (!!!!). 

The methods `form.valid()` should return `false` if any field does not check out, including required ones that are blank, without marking any field with error messages. There are other methods for that!

**Comment by staabm** [comment]
> I just came across this, while performing form.valid() and saw that it returned true, even though some required fields were blank (!!!!).

@yanickrochon please open a separate issue with a jsfiddle so we can reproduce the issue.
