### ISSUE TITLE
Add option for trimming leading and trailing whitespace.

### ISSUE THREAD

**Issue by jgehrcke** [jquery-validation/jquery-validation#1354]
I agree that, generally, leading/trailing whitespace should not be ignored. This was already discussed here:  #874 

However, when using the `url` or `email` type of validation I noticed that it is difficult to provide proper help messages to users considering that leading or trailing white space currently prevents successful validation. So, when a URL does not validate as of leading or trailing white space, the user of the website might not discover the reason her/himself and finally give up, considering the website as "broken". I do not want to annoy these users, so I need to provide a proper help message. Currently, it could read like this:

```
Please provide a proper URL, and take care to not include leading or trailing whitespace.
```

Honestly, I do not want to have such complex help messages. So, before validating, I might want to automatically replace form values with trimmed versions. However, this is something that jquery-validation could also do for us, with a simple option, like so:

```
        rules: {
          websiteurl: {
            url: true,
            required: true
            remove_lt_whitespace: true
          },
          ...
        },
```

Given that, the validation method should first trim the value, replace the value in the form, and only then validate.

Thoughts?

**Comment by JamoCA** [comment]
@jzaefferer I attempted to bind a blur trim function (to email & url class fields) before initializing the validation and it didn't work.  I also used your sample code from JSBin and placed it `$('form').validate();`.  I need more than just the `normalizer` function because we also perform server-side validation. (The actual value needs to be trimmed upon form submission, not just trimmed during internal validation.)
