### ISSUE TITLE
JqueryValidate and Datepicker

### ISSUE THREAD

**Issue by Covivo** [jquery-validation/jquery-validation#1652]
Hello,

I try to validate tow datepicker field's, but i want validate this field only when i submit my form.

For that i turn to false: onblur, onfocusout, onkeyup.

My text field work good,

but when i choose any date from my datepicker, the input is going to validate. 

I guess that's the jQuery Datepicker change value after click. Is not Focusout or keyup...

I don't know if Jquery Validate use a method like : valueChange:false ...? or if existe any method for disabled validate after change value.

Thanks for reading,

sorry for my english !

**Comment by staabm** [comment]
Could you provide a jsfiddle demonstrating your issue and describe the steps required?

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them a long time ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!
