### ISSUE TITLE
date/dateISO do not check days of month correctly

### ISSUE THREAD

**Issue by jmp909** [jquery-validation/jquery-validation#1861]
as of here: https://jqueryvalidation.org/dateISO-method/

both of these dates don't validate correctly, they should fail

2011-11-31
2011-02-29

normally i would use this which checks the data parsed from the input string matches the supplied date

``` javascript
var d = new Date(Date.parse(str))
return str === (d.getFullYear() + '-' + (d.getMonth()+1) + '-' + d.getDate());
```

since 2011-02-29 would parse as 2011-03-01, then this would fail properly

please advise

thanks
J

**Comment by Arkni** [comment]
The `date` method should not be used since it relays on the `Date` constructor which behaves differently across browsers. It's stated clearly in [the docs of this method](https://jqueryvalidation.org/date-method/).

As for the `dateISO` method, there is a PR that adds sanity checks (#1528) to the method but not merged yet, as it could be considered a BC break for those who still rely on the old behavior (even though it's wrong).
