### ISSUE TITLE
not work in IE7 and IE8

### ISSUE THREAD

**Issue by chengang0621** [jquery-validation/jquery-validation#1909]
i use jquery-1.11.0 and jQuery Validation Plugin - v1.16.0，it works in Firefox and chrome ,but not work in ie7 and ie8，how to fix it

**Comment by staabm** [comment]
Please provide a jsfiddle or similar which demonstrates the problem

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them long time ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!
