### ISSUE TITLE
numberOfInvalids() does not count invalid fields that have no error message

### ISSUE THREAD

**Issue by snobo** [jquery-validation/jquery-validation#1922]
Don't know if this behavior is intended or not, but I think it's at least questionable, hence my issue report.

So, method `numberOfInvalids()` does not count invalid fields _that have no error message_. I think it's perfectly valid to have empty error message for certain type of validation, depending on the way errors are indicated; and an invalid field with zero-length error message is still invalid. However,  method `objectLength()` called by `numberOfInvalids()` only counts non-empty values:

```javascript
objectLength: function( obj ) {
	var count = 0, i;
	for ( i in obj ) {
		if ( obj[ i ] ) {
			count++;
		}
	}
	return count;
}
```

why is it so? Shouldn't the condition `if ( obj[ i ] )` be replaced with, say, `if ( typeof obj[ i ] != 'undefined')` or just dropped?

**Comment by Arkni** [comment]
It was intended by me. I made that change more than a year ago in order to fix a bug in validation (See commits 737630e7888485882c8c65b0f8ac5328950be0ac and 7d74fc4157a6f9b29e51af044885cdf72d8654e5). So, I set it to not count elements that are falsy, because the object `this.invalid` may contain properties that are equal to `false` (e.g. [`src/core.js#L469`](https://github.com/jzaefferer/jquery-validation/blob/37f2f3f20af4f4d2a2f80984cd5b39bfa9ff8f09/src/core.js#L469)).

By the way, a field can't have a zero-length error message because `jquery-validation` will assign a default error message to it if that's the case (See [`src/core.js#L824-L832`](https://github.com/jzaefferer/jquery-validation/blob/37f2f3f20af4f4d2a2f80984cd5b39bfa9ff8f09/src/core.js#L824-L832)). So, that change is still valid and doesn't break any code AFAIK.

**Comment by staabm** [comment]
@Arkni thx for your analysis.

@snobo any input why this renders a problem for you? What are you trying to achieve.

**Comment by staabm** [comment]
Will close for now because of inactivity. Feel free to ask further questions/provide furhter information regarding this topic here. We can re-open if required.

**Comment by snobo** [comment]
Sorry for the late reply. Answering both questions now.

@Arkni 
> a field can't have a zero-length error message because jquery-validation will assign a default error message to it if that's the case

Well, default error message can be empty too :) And that's exactly what I set in my code:
`$.validator.messages.required = "";`

@staabm 
>any input why this renders a problem for you? What are you trying to achieve.

As mentioned above, I set an empty error message for Required method, and only mark unfilled required fields visually via CSS (error messages for all other validate methods are still displayed). So, with such configuration, I have a problem with Remote method, which has a call to `validator.resetInternals()` in its `success()` callback that marks all the form fields as valid, even if they are currently invalid.  See #1907 and my comment.

**Comment by staabm** [comment]
I see, that makes sense. not sure whether "not showing a error" is good usability/accessibility wise (maybe you should just hide them via CSS instead?) though.

people not able to see the different color will not notice the error.

**Comment by snobo** [comment]
I agree with the usability concerns. In my case, it's not only a color but an icon; but anyway, chances are I will reconsider my scheme somehow. But still, regardless of that, I just thought that the whole idea of counting invalid elements by their error messages is a bit flawed.

**Comment by staabm** [comment]
As I see it `numberOfInvalids` returns the number of errors visible to the user (which is not technically all errors). from this point of view it looks correct as is (we should document it better, as we have the mentioned edge cases). 

In case someone really needs all occured error he can either do a `.length` or similar on the "errors" array.

**Comment by snobo** [comment]
Mmmm, I just noticed that I confused the problem cases and referenced the Remote method issue incorrectly. I have updated my comment above. So, in this case the problem is indeed simply in `numberOfInvalids` returning wrong number of invalid elements, in case when Required message is empty.

**Comment by Arkni** [comment]
> Well, default error message can be empty too :) And that's exactly what I set in my code:
> `$.validator.messages.required = "";`

Didn't expect someone will use that :-)

Your version will report incorrect values. As I said in my previous comment, I did the change because `this.invalid` may contain falsy values but I didn't expect that someone will have the same use case as yours, so didn't bother looking for `false` values.

I think we have to change the test to be more strict. That way, we will never be hit by edge cases:
```js
if ( obj[i] !== undefined && obj[i] !== null && obj[i] !== false ) {
  // ...
}
```

I will do that in a followup PR as soon as I have some free time.

**Comment by Giplo** [comment]
I had the same problem and I used this workaround:

`$.validator.messages.required = " ";`

with a blank space
Thanks for the fix...!!
