### ISSUE TITLE
Mixed content in demos

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#1939]
> @markusstaab Hi. Auf jqueryvalidation.org/files/demo/mul… wird jQuery UI per HTTP geladen, triggered mixed content error.

https://twitter.com/m_strehl/status/827655221467820036

**Comment by Arkni** [comment]
@staabm are you able to handle this issue ?

**Comment by staabm** [comment]
Feel free to take it over. My time is rather limited in the last weeks/months

**Comment by Arkni** [comment]
@staabm 

I took a quick look into it, and it seems I only need to update the links in files that are part of the `demo` folder found in this repo.

I can also update some links in docs to use `https`, but that will not fix the current issue.

_In case you have access to the filesystem on `jqueryvalidation.org`_:
* We will need to update the `demo` folder under `files` to the one we have currently in this repo.
* We might also need to change the mapping (it might be an `.htaccess` file) that maps `../lib/jquery.js` to version `3.1.1` from [`aspnetcdn`](https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js). I think that mapping is wrong, because it also catch `../../lib/jquery.mockjax.js` and maps it to the same url of `jquery`, which is wrong.

**Comment by staabm** [comment]
> In case you have access to the filesystem on jqueryvalidation.org:

I recently got the password to access the folder. so we are good to go :)

**Comment by Arkni** [comment]
Good!

I pushed a commit to master and created jquery-validation/validation-content#34

I didn't want to link this issue and the other one shown above as we didn't deploy the changes yet.

**Comment by staabm** [comment]
Just pushed the changes from @Arkni and update the demos.

Great Job @Arkni, txh!

https://jqueryvalidation.org/files/demo/

**Comment by Arkni** [comment]
Thanks @staabm 

I think there still one small issue that can be solved in another day. It's about the [`Remember The Milk signup form`](https://jqueryvalidation.org/files/demo/milk/) (Open the console). The cause is this as I mentioned in my previous comment https://github.com/jquery-validation/jquery-validation/issues/1939#issuecomment-293566133:
> We might also need to change the mapping (it might be an `.htaccess` file) that maps `../lib/jquery.js` to version `3.1.1` from [`aspnetcdn`](https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.1.1.min.js). I think that mapping is wrong, because it also catch `../../lib/jquery.mockjax.js` and maps it to the same url of `jquery`, which is wrong.

**Comment by staabm** [comment]
@Arkni I guess the mapping is happening here:

https://github.com/jquery-validation/jquery-validation/tree/bb0c335c7ad44765569426d60977cdf5666849cb/lib

especially https://github.com/jquery-validation/jquery-validation/blob/bb0c335c7ad44765569426d60977cdf5666849cb/lib/jquery.js

**Comment by staabm** [comment]
hm I am in contact with the admin as the files on the webroot are not served by our server but redirected by cloudflare instead..

**Comment by staabm** [comment]
we fixed the cloudflare rules..

**Comment by Arkni** [comment]
Good job :+1: 

Thanks for the heads up :)
