### ISSUE TITLE
Prepare new release

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#2016]
- any issues left?
- changelog (@Arkni)
- blogpost (@Staabm)
- merge https://github.com/jquery-validation/validation-content/pull/33 and deploy docs

**Comment by Arkni** [comment]
* There still one issue I want to fix (#1596) but it needs some testing. I'll see if I can add some tests for it before the next release.
* jquery-validation/validation-content#33 is ready to merge.
* For the changelog, I will generate one this evening.

**Comment by staabm** [comment]
great job @Arkni . With a regenerated changelog including the latest addtion we are good to go.

**Comment by Arkni** [comment]
Latest changes have been added to the changelog!

**Comment by staabm** [comment]
ohh my. new workstation.. seems our current grunt workflow does not work with win10 or node8.2+ or similar.

```
~\Documents\GitHub\jquery-validation [master ≡]> grunt
Running "concat:dist" (concat) task

Running "concat:extra" (concat) task

Running "copy:dist" (copy) task
Copied 61 files

Running "jscs:all" (jscs) task
>> 120 files without code style errors.

Running "jshint:core" (jshint) task
>> 112 files lint free.

Running "jshint:test" (jshint) task
>> 7 files lint free.

Running "jshint:grunt" (jshint) task
>> 1 file lint free.

Running "qunit:files" (qunit) task
Testing test/index.html Warning: Cannot read property 'pid' of undefined Use --force to continue.

Aborted due to warnings.
```

hopefully on my old laptop at home things still work.

@Arkni do you have an idea what the problem could be? do we need to update dev-libs or similar to support newer node version?

**Comment by staabm** [comment]
released 1.17.0 in https://github.com/jquery-validation/jquery-validation/commit/365453a6c87848e6bc3f8cfdbbf5cfae923449de

still we need to figure out why it doesnt work with a more up2date setup :-/

**Comment by Arkni** [comment]
Sorry for not responding quickly.

I remember seeing that error a year ago. If I recall correctly, that error happens because `PhantomJS` was not installed.

We use `grunt-contrib-qunit` which in turn use `grunt-lib-phantomjs` that use  [`phantomjs-prebuilt`](https://github.com/Medium/phantomjs) to install and provide back the path of `PhantomJS` binary.

Sometimes, the downloading process got interrupted by the hosting service in which `PhantomJS` binaries were hosted (`Bitbucket` or `GitHub`) mainly because of rate limit. Also, it may happen during the decompressing of the archive that contains the binary because of a mismatch between the calculated `sha256` digests.

A common fix is to remove `grunt-contrib-qunit` and reinstall it. This fixes the error most of the time :)

What I do myself is downloading the binary myself and adding the binary path to `%PATH%`. That way, `phantomjs-prebuilt` will use the globally installed binary and skip the download process.

Finally, thank you for the release :)

**Comment by Arkni** [comment]
Will close this issue as `1.17.0` has already been released.
