### ISSUE TITLE
Array not validating.

### ISSUE THREAD

**Issue by shankhadevpadam** [jquery-validation/jquery-validation#2046]
i have the dynamic input like below how to validate like this. Only first field is validate

```html
<input type="text" name="arrival_time[]" required>
<input type="text" name="arrival_time[]" required>
<input type="text" name="arrival_time[]" required>
```

**Comment by Arkni** [comment]
The `name` attribute must be unique to the form, as this is how the plugin keeps track of all input elements. However, it is allowed to use the same name for `radio` buttons and `checkbox`s.
So each group of radio or checkbox elements will share the same `name` since the value of this grouping represents a single piece of the form data.

They were many requests in the past from the community to add support for it, but the lack for time and/or people who are willing to implement it results in what you see now.

I would like to work on it, but my current situation doesn't help with that. So I promise nothing.

**Comment by aivils** [comment]
I manually applied this https://github.com/jquery-validation/jquery-validation/pull/2000
And it works for me.
