### ISSUE TITLE
Missing translation for remote

### ISSUE THREAD

**Issue by vanillajonathan** [jquery-validation/jquery-validation#2064]
Some translation lack a translation for the 'remote' field.

* https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_da.js
* https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_fi.js
* https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_no.js
* https://github.com/jquery-validation/jquery-validation/blob/master/src/localization/messages_sv.js

Danish, Finish, Norweigan and Swedish translations lack a translation for 'remote'.
Maybe other translations lack translations for 'remote' too.

**Comment by Arkni** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this?

**Comment by vanillajonathan** [comment]
It would be good if we could ping some translation maintainers or people who have previously contributed since they have first hand knowledge of languages.
So we can get something better than [Google Translate](https://translate.google.com/). :P

The string in need of translation is "Please fix this field."

Strings translated by Google Translate:
* da: Ret venligst dette felt.
* fi: Korjaa tämä kenttä.
* sv: Var snäll och åtgärda detta fält.
* no: Vennligst reparer dette feltet.

I don't know about the others, but the Swedish translation sounds pretty good.

**Comment by Arkni** [comment]
> It would be good if we could ping some translation maintainers or people who have previously contributed since they have first hand knowledge of languages.

That would be hard knowing that almost all translation files were added by `Jörn` in [`the first commit`](https://github.com/jquery-validation/jquery-validation/commit/ce7c5baa4e513d5fe168c315c47cab25a1ea4f80) 8 years ago, and we have no information about who originally contributed the translation.

There are some people that contributed some fixes 4-5 years ago, and it will be awkward to just ping them here given the fact that they are not active/one time contributors, and maybe have switched the carer and/or stopped contributing to open source (due to some reason).

Maybe we will just let that as is, and if someone needs translation of an error message in their native language, we will then ask them to contribute it.

As for the Swedish translation, can you open a PR for that?

**Comment by HawkonDK** [comment]
Pull [2067](https://github.com/jquery-validation/jquery-validation/pull/2067) add Remote for messages_da.js

**Comment by vanillajonathan** [comment]
Reference #2067
