### ISSUE TITLE
Jquery prop checked to true will not auto hide error text

### ISSUE THREAD

**Issue by yuyenkan** [jquery-validation/jquery-validation#2089]
### Subject of the issue
Jquery prop checked to true will not auto hide error text

### Environment
Latest version of jquery-validation
Microsoft Edge 38.14393.1066.0
Microsoft EdgeHTML 14.14393

### Steps to reproduce
https://jsfiddle.net/a8bv992s/

### Expected behaviour
When parent checkbox checked, jquery change child checkbox checked state, and the error label show be hide.

### Actual behaviour
Parent checkbox is checked, and child checkbox is also checked by jquery, but the error label is remain until submit button is clicked.

**Comment by Arkni** [comment]
When changing the value of an element programmatically, you should revalidate the element yourself using [`.valid()`](https://jqueryvalidation.org/valid/) or [`Validator#element()`](https://jqueryvalidation.org/Validator.element/).
Because jQuery-validaion will not be informed by your change. jQuery-validation only listens to user events like `click`, `keydown`, `keyup` ...

**Comment by yuyenkan** [comment]
Currently what I did is programmatic show the error text, seem like working but not sure will have any others problem with it or not.

I know I can use .valid() to validate whole form, but in that time whole form validate is not very proper as user only clicking on a part of form. Because it is a group of nested checkbox, so a group of element validation is hard for me, I tried to use validate by class, but there is unknown problem whole form validation gone when I declare that.
