### ISSUE TITLE
URL validation issue

### ISSUE THREAD

**Issue by jeradrutnam** [jquery-validation/jquery-validation#2128]
### Subject of the issue
URL validation regex is wrong. As it will not match the url: http://localhost:8080/callback, which is a valid url.

### Your environment
* version: 1.17.0
* browser: google chrome

### Steps to reproduce
Test above url with: https://jqueryvalidation.org/url-method/

### Expected behaviour
Should accept as a valid url

### Actual behaviour
Return as an invalid url

**Comment by Arkni** [comment]
Hi @jeradrutnam 

The regex used by the `url` method is based on [`this gist`](https://gist.github.com/dperini/729294) (with a small change) which is developed in order to validate the most common used urls (so this regex will consider `http://localhost/`, `http://localhost:8080/` as invalid).

Following is a comment from the regex source code:

``` js
// the regular expression composed & commented
// could be easily tweaked for RFC compliance,
// it was expressly modified to fit & satisfy
// these test for an URL shortener:
//
//   http://mathiasbynens.be/demo/url-regex
//
// Notes on possible differences from a standard/generic validation:
//
// - utf-8 char class take in consideration the full Unicode range
// - TLDs have been made mandatory so single names like "localhost" fails
// - protocols have been restricted to ftp, http and https only as requested
//
// Changes:
//
// - IP address dotted notation validation, range: 1.0.0.0 - 223.255.255.255
//   first and last IP address of each class is considered invalid
//   (since they are broadcast/network addresses)
//
// - Added exclusion of private, reserved and/or local networks ranges
//
// - Made starting path slash optional (http://example.com?foo=bar)
//
// - Allow a dot (.) at the end of hostnames (http://example.com.)
```

In case you need to accept local urls, please consider [`redefining`](https://jqueryvalidation.org/jQuery.validator.methods/) the `url` method with a custom RegExp.

The implementation of that method in core is unlikely to change in the near future as it was the default implementation for the last 5 versions.

Closing this for now, feel free to ask if you have follow up questions.

**Comment by jeradrutnam** [comment]
Hi @Arkni,

I understand. Thanks for the nice explanation. I will go with a custom regex for the moment as mentioned. :)

Cheers!

**Comment by Jogai** [comment]
Here is a nice one as well: https://gist.github.com/gruber/249502

Its more liberal, so take care.
