### ISSUE TITLE
Validation not working on textarea of dynamic form.

### ISSUE THREAD

**Issue by bchdubois** [jquery-validation/jquery-validation#2137]
I am trying to get validate to work with a form I create. I create the form dynamically (on the fly) and when they click the "Add" button I run validate.

    	var formValid = false;
        if (planningEventValidators[this.eventType].valid()) {
            console.log("Valid form");
            formValid = true;
        } 
        return formValid;

I have the following code(below) where I initialize the validate. And below the code is a screen capture from the browser of the Console, I run the validate manually and it returns true, even though admissionDetails is blank/empty.

I am using CHROME.

Help Please!
J

	planningEventValidators[this.eventType] = $("#" + this.eventType + "FormId").validate({
		errorContainer: $validateErrorBox,
		errorLabelContainer: $("ul", $validateErrorBox),
		wrapper: 'li',
	    errorClass: "error",
	    validClass: "",
	    rules: {
	        dayCount: {
	            required: true,
	            number: true
	        },
	        iaLocation: {
	            required: true
	        },
	        icuBed: {
	        },
	        admissionDetails: {
	            required: true,
	            minlength: 5
	        }
	    },
	    // Custom Error Message (default is Field is required)
	    messages: {
	        iaLocation: "Location selection is a required",
	        admissionDetails: "Admission Details are required",
	        icuBed: "ICU Bed selection is required",
	    }
	});

Below is screen capture from browser where I run valid() manually (for testing). As you can see from the console.log, admissionDetails value is empty, when I run the valid() method it returns true even though it has a rule for admissionDetails(required/minlenght 5).
![Browser code](http://miniworld.com/temp/planningEventValidation01.png)

# EDIT
I got it at least somewhat working and (after stripping down a lot of code) got it up on Fiddle.

It currently shows the error container but I have to manually call submit on the form, where as when I have it as a static popup, it calls it when I close the dialog box. Also it does not display the actual error message until you click somewhere in the background of the popup.

### Steps to reproduce

* Load [Fiddle Example](https://jsfiddle.net/duboisjsf/yn749w77/)
* Click  "Admit" button, which brings up a popup with two fields. 
* Click "Add Event" button, which should throw error because Admission details is empty.

**Comment by bchdubois** [comment]
Any thoughts on this????

**Comment by Arkni** [comment]
Hi @bchdubois 

I did a quick look at your code, you demo sometimes is working as you described and sometimes I don't see any error message. But, here are my thoughts so far:

* If I'm not wrong, you're initializing the validator in your code after opening your dialog (using `dialog("open")`) which I tend to think that the validator will not be initialized as the form doesn't exist on DOM yet due to the modal is not rendered yet. If that's the case, you should call `$("form selector").validate(options)` after the modal is shown. To do that, listen to [`dialogopen`](http://api.jqueryui.com/dialog/#event-open) event and initialize the validator inside the event handler.
* I also see that you try to initialize the plugin inside the click handler of your button. You don't need to do that. The plugin is design to be initialized only once, any subsequent call will only return the created plugin instance on your form.

I will try to do another look on your code when I have some free time.

**Comment by paulraines68** [comment]
I had a form using jquery-validation on a section of a page and decided to move it into a Jquery UI Dialog widget.  As soon as I did that validation stopped working.  Moving the .validate() call to inside a dialogopen hook did not fix it.  I think there is something else about these inputs once inside a dialog  that at the time .valid() is called your code assume it can just ignore/filter them.

**Comment by Arkni** [comment]
This issue is fairly old and there hasn't been much activity on it.

Closing, but please ping me to re-open it if it still occurs.

**Comment by vishwakarmanikhil** [comment]
I am facing this issue.
I am using the rich text editor ckeditor5. I have defines rules as required and minlength to textarea but it is not working. can you please let me know if this query is already answered or still this is an isssue.

**Comment by bchdubois** [comment]
@vishwakarmanikhil  I was never able to successfully solve this issue and we ended up writing custom validation to check and then push them onto errors list.

**Comment by vishwakarmanikhil** [comment]
ok, thank you @bchdubois
