### ISSUE TITLE
If I programmatically selecting multiple select2 options , when I trigger a change event on select2 than valid return false but none of the methods like errorPlacement, invalidHadlers, messages are firing

### ISSUE THREAD

**Issue by joydipnath** [jquery-validation/jquery-validation#2145]
### Subject of the issue
When I am programmatically selecting multiple options of a select2 element than I am triggering a change event after which I am validating the form . Now because of the change event form validator is not firing any of these methods errorPlacement, invaliHandle , messages (etc)
But If I dont make a change event than form vaidation works like a charm.
Problem is if I remove triggering change an event than selected options cant be displayed.

### Your environment
* version of `jquery-validate` - v1.16.0
* which browser and its version - chrome Version 64.0.3282.167 - ubuntu
* select2 version : Select2 4.0.3

**Comment by Arkni** [comment]
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them 20 days ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!
