### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gimler** [jquery-validation/jquery-validation#2188]
Can you please make a new release. Because the last one is 1 year old.

**Comment by staabm** [comment]
@Arkni do you see any known issues which need to be solved before we create a new release?

**Comment by Arkni** [comment]
Hi @gimler & @staabm 

Sorry for taking so long to respond to this. It was a crazy month for me.

Yes, I do have some issues in my todo list that I would like to see fixed before the next release.
These issues are:
* #2042: submitHandler still get triggered when debug is true
* #2094: Unnecessary aria-describedby attribute causes WCAG scans to fail
* #2141: Object doesn't support property or method 'hasAttribute' error appears on old IE browsers (_PR #2142_)
* #2158: Uncaught TypeError: Cannot read property 'settings' of undefined (_for good this time, because I had the impression we already fixed it, but I might be wrong_)

I would also like to merge some (or all if possible) of these pull requests:
* #2074: Core: Add multiple attribute to email method
* #1973: HexColor method

 I hope to fix these in the next two or three weeks (depends on my schedules).

Thanks for the reminder.

**Comment by staabm** [comment]
Thank you arkni for working on these issues.

Take your time and give me a ping in case we are ready to go, or change the things we need to incluse before the next release.

Thanks again

**Comment by Arkni** [comment]
Hi @staabm,

Sorry for taking so long to work on this. I'm a little depressed the last few days and I can't work on the remaining issues and PR. Until I or someone else could, could you please release the current master branch? the remaining issues and PR can be then included in another release.

Thanks a lot :) And sorry for the delay!

**Comment by staabm** [comment]
@arkni dont stress yourself with this project. 

You already do an amazing job.  We release what we have and in case we need more we can do another release whenever we have something at hand.

Thanks again, I will create a release after beeing home from vacation

**Comment by reloxx13** [comment]
so one more year without updates, gg

- create new release with list of your known issues
- fix issues
- create new release
-profit

there will always be some bugs, if this goes on we will never see an update...

im using composer for your repo and have no access to install/use npm/grunt, and i dont want packages hardcodes/builded from local in the git.

so yep, 1 year old zip release with bugs which got already fixed months ago.
and be sure, if the project is done, i wont touch this repo again.

hope you understand my point of view.

**Comment by nj** [comment]
@staabm Do you know who have upload to [Microsoft Ajax Content Delivery Network](https://docs.microsoft.com/en-us/aspnet/ajax/cdn/jquery-validate/)?

Would be great if the upcoming release, that the `localization` files actually matches the expected content, hence the `dist` versions with the *UMD wrapper* used in the `npm` release.

The currently version (`1.17.0`) breaks `integrity`, like the case for i.e. [`messages_da.js`](https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/localization/messages_da.js).

Older versions doesn't seems to have this issue regarding the language files :wink:

**Comment by staabm** [comment]
@Arkni could you generate a changelog?

**Comment by staabm** [comment]
tagged new 1.18.0 release https://github.com/jquery-validation/jquery-validation/releases/tag/1.18.0

its already uploaded on npm and will be published within the next hours/days on the CDNs (should happen automatically on jsdelivery and cdnjs).
MS ajax-cdn was notified manually  and they should upload the release in the coming few days.

@reloxx13 feel free to spent your free time on this project like we - the maintainers do. we do this whole project besides our regular jobs for 0 money.

**Comment by staabm** [comment]
@Arkni  could the `integrity` problem mentioned in https://github.com/jquery-validation/jquery-validation/issues/2188#issuecomment-419431306 be our own fault?

**Comment by nj** [comment]
@staabm The issue is basically that the `umdStart`, `umdMiddle` and `umdEnd` parts were missing - like the file uploaded to CDN was the one in `src` (without `UMD`), rather than the one in `dist` (with `UMD`).

It's properly fixed already in relation to #2057 included in `1.18.0`, which will include all needed files now - avoiding any additional manual action.

Could basically have been the manual process by MS mentioned in your comment, where someone at MS had picked the wrong set of files, when it's not automated.

I'll confirm when CDN is updated :wink:

**Comment by Arkni** [comment]
@staabm 

We were part of it. Up to 1.17.0, we didn't publish the localization files (minified files included) to GitHub. So, it's the person, thanks for their help, who uploaded the files to MS CDN that used the wrong files (as @nj said).

I hope it can be fixed with the current release.

Also, thanks for the release :)

**Comment by nj** [comment]
Seems like [Microsoft](https://docs.microsoft.com/en-us/aspnet/ajax/cdn/jquery-validate/) hasn't updated the CDN yet, though it has been more than a month by now 😕
