### ISSUE TITLE
Async Await support

### ISSUE THREAD

**Issue by artemsky** [jquery-validation/jquery-validation#2264]
### Environment
* `"jquery": "3.3.1"`
* `"jquery-validation": "1.17.0"`
* Chrome 72

### Steps to reproduce
```
$form.validate({
    async submitHandler(form) {
        const { data } = await Api.store(form);
        // ... any code here
    }
})
```
### Expected behaviour
Async function works

### Actual behaviour
It doesn't work. Page redirects after submit.

**Comment by aimyth** [comment]
Any update on this issue.
Since others were local request, it made sense to call it synchronously. The submit alone is making a network request to the api server or web server proxy which would need this support.

I am assuming this would read the async keyword mentioned by @artemsky  or have another handler named 
<pre>
// Read the async keyword and don't submit the form
SubmitHandler: async (form) => {
    const { data } = await Api.store(form);
     // ... any code here
}

// Have separate handle and don't submit the form
asyncSubmitHandler: async (form) => {
    const { data } = await Api.store(form);
     // ... any code here
}
</pre>
Note:
The async function does get called in the submit handler but it doesn't prevent the page reload.

**Comment by aimyth** [comment]
The following is the workaround inside the submit handler
<pre>
(async () => {
         const { data } = await Api.store(form);
 })();
</pre>
