### ISSUE TITLE
Calling either .element(...) or valid(...) returns true even when element invalid

### ISSUE THREAD

**Issue by jarfer** [jquery-validation/jquery-validation#2267]
Calling either .element(...) or validate(...) returns true in all cases, even when element is invalid.

Here is a working fiddle of a fairly simple form showing this https://jsfiddle.net/Le30b4da/1/ try clicking "Test postcode is valid" this will always return true, even though postcode is required and can be either empty or non-empty.

This same issue has been separately by different people at different times but closed without sensible reasons given:

https://github.com/jquery-validation/jquery-validation/issues/823
https://github.com/jquery-validation/jquery-validation/issues/965
https://github.com/jquery-validation/jquery-validation/issues/1045

I understand you may not wish to acknowledge this issue as I doubt this was the way in which jQuery Validation was intended for use, but in this case I would then recommend updating your documentation accordingly to avoid wasting other people's time:  https://jqueryvalidation.org/Validator.element/

**Comment by TamaKun89** [comment]
.valid() checks and returns true or false when the validation is initialized, the javascript provided in the fiddle  was just confusing and didn't make any sense, your function isValid() always returns true because it says "return true".

I forked your fiddle and corrected it so it works as intended. I hope this will help anyone else to not get confused by this issue:

https://jsfiddle.net/xq9u3zbo/

**Comment by molihub** [comment]
As I wrote in issue #956 remote validation causes double submit, I found a solution like below can avoid some case temporary.
```
theForm.on("submit", function(e) {
    if (!theForm.valid() || theForm.find("input." + this.validator.settings.pendingClass).length) {
         // attention: I have this.validator in my code.
         return false;
    }

    // ...
}
```
