### ISSUE TITLE
release 1.19.1

### ISSUE THREAD

**Issue by staabm** [jquery-validation/jquery-validation#2287]

**Comment by staabm** [comment]
done with https://github.com/jquery-validation/jquery-validation/commits/1.19.1

**Comment by staabm** [comment]
published on npm.

**Comment by staabm** [comment]
MS CDN contact informed about the release

**Comment by staabm** [comment]
@Arkni hmm... I guess something went not 100% correct and the commit for 1.19.1 did not appear in the master branch:

https://github.com/jquery-validation/jquery-validation/commit/3cdad0bc8dc1e6fbd34c1e3225598f80cfd97a48

could you double check if something went wrong?

**Comment by Arkni** [comment]
Hi @staabm,

Sorry for taking so long to answer and being active in this repo. I haven't been active that much in the last 5 months for some health issues. And because of that, I have taken a long break from open source and some other activities.

---

Thanks a lot for creating the release :)

> I guess something went not 100% correct and the commit for 1.19.1 did not appear in the master branch:

I don't see any anomaly. It's the way `jquery-release` works. It creates the release on a temporary detached branch and then delete it. The commit and the tag are still there. The release commit will not appear on the master branch, just as it was for the previous releases (If I recall correctly, it was suggested by Jörn to be implemented this way years ago).

**Comment by staabm** [comment]
Ok thx for checkin.

Please take as much time as you need to get well. Your health is way more important then anything happening here. Fingers Crossed

**Comment by Arkni** [comment]
I doing good now :) I just need some more time to make sure everything is back to its place.

Thanks :)
