### ISSUE TITLE
missing .groups('add/remove', [group])

### ISSUE THREAD

**Issue by Yahasana** [jquery-validation/jquery-validation#247]
RT

**Comment by arfmach** [comment]
I've created a wrapper API to be used by our company's webdesigners. It uses a JSON structure to set up both validation and typing masks, so that they don't need to know anything about jquery-validation nor masks. Obviously, I dynamically add all rules after validate(), by calling $("#field").rules("add", rule). The've come up with a new need where one of two fields are required; I managed to achieve that by using required:"#otherfield:blank", but error message from second field doesn't hide when user fills first field or vice-versa. The only way I've found to handle it is by grouping, but since I'm adding rules dynamically, I'd need to add groups dynamically too.

**Comment by geoidesic** [comment]
Please can we re-open this?

Here are some stack-overflow questions asking for the same thing, dynamic groups, like you have dynamic rules.

http://stackoverflow.com/questions/34955698/jquery-validate-how-to-add-groups-dynamically
http://stackoverflow.com/questions/26125537/jquery-validate-populate-groups-dynamically

My suggestion is that you allow groups to accept css selectors instead of just the "name" attribute for collection purposes. That way you don't need to know the names of the fields before run-time.

**Comment by plocket** [comment]
Has there been any progress on this? Is there a separate issue now?
